language: objective-c
osx_image: xcode8

env:
  - "DESTINATION='platform=watchOS Simulator,name=Apple Watch - 38mm' ACTION=build"
  - "DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p' ACTION=build"
  - "DESTINATION='platform=OS X' ACTION=build"

script:
  - set -o pipefail && xcodebuild -project Toast.xcodeproj -scheme Toast -destination "$DESTINATION" $ACTION | xcpretty
